### ISSUE TITLE
Default to global ipfs API

### ISSUE THREAD

**Issue by danfinlay** [ipfs/go-ipfs-gateway#10]
The [ipfs companion](https://github.com/ipfs-shipyard/ipfs-companion) browser extension allows a user to provide a web API to any site that draws data from the user's own IPFS client preference.

When loading the IPFS gateway, it would be cool if the site first checked if the user's browser had a `window.ipfs` object, as provided by the [ipfs companion](https://github.com/ipfs-shipyard/ipfs-companion), and defaulted to loading content from it.

This would reduce load on the gateway when visited by companion users, and would also allow links to ipfs gateways to serve as links to ipfs-browser-users' own local caches.

It's no `ipfs://`, but it would be a lot easier to make happen.

**Comment by Stebalien** [comment]
The IPFS companion can already redirect requests from `https://ipfs.io` to `http://localhost:8080`.

We *also* have a js based gateway (currently hosted at https://js.ipfs.io) that installs a service worker that, in turn, uses js-ipfs. See: https://github.com/ipfs-shipyard/service-worker-gateway. It *may* also be possible to get the IPFS companion to install this service worker on-behalf-of `https://ipfs.io` (to redirect all requests to the extension transparently). We don't have this setup on ipfs.io by default mostly because it's still experimental (and js-ipfs has some significant performance issues).

Take a look at https://github.com/ipfs-shipyard/ipfs-companion/issues/248 and the related issue.

---

Unfortunately, the go-ipfs gateway can't really do any of this itself as it's *just* an HTTP gateway and is expected to serve resources to arbitrary HTTP clients (it can't assume that it's *just* being used to serve websites).

Closing for tracking purposes as this is more of a ipfs-companion issue than a go-ipfs issue. Feel free to ask followup questions.
