### ISSUE TITLE
Investigate WebDAV support

### ISSUE THREAD

**Issue by ghost** [ipfs/go-ipfs-gateway#9]
Some of the WebDAV methods might be useful on the gateway.

Reading list:
- [RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)
](https://tools.ietf.org/html/rfc4918)

**Comment by Kubuxu** [comment]
Assigning myself so I remember to read it.

**Comment by Admin-DataRoads** [comment]
IIRC both Subversion and Mercurial have WebDAV compatible HTTP/S interfaces, for comparison sake. Neither is anywhere close to supporting the full RFC set of commands and semantics, because that spec turns out to be complete overkill for real world version control use cases. Mercurial and Git obviously ignore all the lock semantics, and no VCS really deletes anything -- although I would argue distributed consensus locks and "please forget" or "oops ignore mistake" pruning style requests among known peer sets, for example via Paxos or Raft, should all be doable. 

Mercurial has some limited "oops ignore mistake" style pruning support via changeset evolution commands, but no easy way to distribute consensus on such requests among known peers. That limited pruning support still makes Mercurial manifests a good example to look at for future WebDAV-IPNS development.

I saw the "help wanted" sign, and thought this might be a good place for me to learn Go IPFS code, although as a n00b I would appreciate a more experienced advisor. ;) It looks like Go already has a library for this.

[https://godoc.org/golang.org/x/net/webdav](https://godoc.org/golang.org/x/net/webdav)

**Comment by zicmama** [comment]
anyone have found a Webdav way to access IPFS? It would give a huge compatible clients...

**Comment by pataquets** [comment]
Would love this, too.
The nearest I found when looking for it a while ago is mattn/davfs#3.

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/in-web-browsers/issues/146
